<?php

/**
 * @file
 * This is a Drupal 11 settings.ddev.php file automatically generated by DDEV.
 *
 * DDEV manages this file and may delete or overwrite it unless this
 * comment, marked with #ddev-generated, is removed. It is recommended
 * that you leave this file alone.
 */

$host = "localhost";
$port = 3306;
$driver = "mysql";

$databases['default']['default']['database'] = "c5_dcgardens";
$databases['default']['default']['username'] = "c5c5";
$databases['default']['default']['password'] = "Pep_8SYungJ";
$databases['default']['default']['host'] = $host;
$databases['default']['default']['port'] = $port;
$databases['default']['default']['driver'] = $driver;

$settings['hash_salt'] = 'f190fd06afffe9b1390aaeb5ac034b83d0cdbf81a86013b0a2117bad01f2dee2';

// This will prevent Drupal from setting read-only permissions on sites/default.
$settings['skip_permissions_hardening'] = TRUE;

// This will ensure the site can only be accessed through the intended host
// names. Additional host patterns can be added for custom configurations.
$settings['trusted_host_patterns'] = ['.*'];

// Set $settings['config_sync_directory'] if not set in settings.php.
if (empty($settings['config_sync_directory'])) {
  $settings['config_sync_directory'] = 'sites/default/files/sync';
}

// Enable verbose logging for errors.
// https://www.drupal.org/forum/support/post-installation/2018-07-18/enable-drupal-8-backend-errorlogdebugging-mode
$config['system.logging']['error_level'] = 'verbose';
$settings['file_private_path'] = '/var/www/clients/client5/web10/web/private_files';
$settings['file_temp_path'] = __DIR__ . '/tmp';
