/* @license GPL-2.0-or-later https://www.drupal.org/licensing/faq */
((Drupal,drupalSettings,once)=>{Drupal.behaviors.ginAccent={attach:function attach(context){once('ginAccent','html',context).forEach(()=>{Drupal.ginAccent.checkDarkMode();Drupal.ginAccent.setFocusColor();});}};Drupal.ginAccent={setAccentColor:function setAccentColor(preset=null){const accentColorPreset=preset!=null?preset:drupalSettings.gin.preset_accent_color;const accentColors=drupalSettings.gin.accent_colors;const presetColor=accentColors[accentColorPreset]['hex'];document.documentElement.style.setProperty('--accent-base',presetColor);},setCustomAccentColor:function setCustomAccentColor(color=null,element=document.documentElement){const accentColor=color!=null?color:drupalSettings.gin.accent_color;if(accentColor){this.clearAccentColor(element);element.style.setProperty('--accent-base',accentColor);}},clearAccentColor:(element=document.documentElement)=>{element.style.removeProperty('--accent-base');},setFocusColor:function setFocusColor(preset=null,color=null){const focusColorPreset=preset!=null?preset:drupalSettings.gin.preset_focus_color;document.documentElement.setAttribute('data-gin-focus',focusColorPreset);if(focusColorPreset==='custom')this.setCustomFocusColor(color);},setCustomFocusColor:function setCustomFocusColor(color=null,element=document.documentElement){const accentColor=color!=null?color:drupalSettings.gin.focus_color;if(accentColor){this.clearFocusColor(element);const strippedAccentColor=accentColor.replace('#','');const darkAccentColor=this.mixColor('ffffff',strippedAccentColor,65);const style=document.createElement('style');style.className='gin-custom-focus';style.innerHTML=`
          [data-gin-focus="custom"] {\n\
            --gin-color-focus: ${accentColor};\n\
          }\n\
          .gin--dark-mode[data-gin-focus="custom"],\n\
          .gin--dark-mode [data-gin-focus="custom"] {\n\
            --gin-color-focus: ${darkAccentColor};\n\
          }`;element.append(style);}},clearFocusColor:(element=document.documentElement)=>{if(element.querySelectorAll('.gin-custom-focus').length>0){const removeElement=element.querySelector('.gin-custom-focus');removeElement.parentNode.removeChild(removeElement);}},checkDarkMode:()=>{const darkModeClass=drupalSettings.gin.dark_mode_class;window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change',(e)=>{if(e.matches&&window.ginDarkMode==='auto')document.documentElement.classList.add(darkModeClass);});window.matchMedia('(prefers-color-scheme: light)').addEventListener('change',(e)=>{if(e.matches&&window.ginDarkMode==='auto')document.documentElement.classList.remove(darkModeClass);});},mixColor:(color_1,color_2,weight)=>{function d2h(d){return d.toString(16);}function h2d(h){return parseInt(h,16);}weight=(typeof (weight)!=='undefined')?weight:50;var color="#";for(var i=0;i<=5;i+=2){var v1=h2d(color_1.substr(i,2)),v2=h2d(color_2.substr(i,2)),val=d2h(Math.floor(v2+(v1-v2)*(weight/100.0)));while(val.length<2)val='0'+val;color+=val;}return color;}};})(Drupal,drupalSettings,once);;
(function($,Drupal,debounce){const cache={right:0,left:0,bottom:0,top:0};const cssVarPrefix='--drupal-displace-offset';const documentStyle=document.documentElement.style;const offsetKeys=Object.keys(cache);const offsetProps={};offsetKeys.forEach((edge)=>{offsetProps[edge]={enumerable:true,get(){return cache[edge];},set(value){if(value!==cache[edge])documentStyle.setProperty(`${cssVarPrefix}-${edge}`,`${value}px`);cache[edge]=value;}};});const offsets=Object.seal(Object.defineProperties({},offsetProps));function getRawOffset(el,edge){const $el=$(el);const documentElement=document.documentElement;let displacement=0;const horizontal=edge==='left'||edge==='right';let placement=$el.offset()[horizontal?'left':'top'];placement-=window[`scroll${horizontal?'X':'Y'}`]||document.documentElement[`scroll${horizontal?'Left':'Top'}`]||0;switch(edge){case 'top':displacement=placement+$el.outerHeight();break;case 'left':displacement=placement+$el.outerWidth();break;case 'bottom':displacement=documentElement.clientHeight-placement;break;case 'right':displacement=documentElement.clientWidth-placement;break;default:displacement=0;}return displacement;}function calculateOffset(edge){let edgeOffset=0;document.querySelectorAll(`[data-offset-${edge}]`).forEach((el)=>{if(el.style.display==='none')return;let displacement=parseInt(el.getAttribute(`data-offset-${edge}`),10);if(isNaN(displacement))displacement=getRawOffset(el,edge);edgeOffset=Math.max(edgeOffset,displacement);});return edgeOffset;}function displace(broadcast=true){const newOffsets={};offsetKeys.forEach((edge)=>{newOffsets[edge]=calculateOffset(edge);});offsetKeys.forEach((edge)=>{offsets[edge]=newOffsets[edge];});if(broadcast)$(document).trigger('drupalViewportOffsetChange',offsets);return offsets;}Drupal.behaviors.drupalDisplace={attach(){if(this.displaceProcessed)return;this.displaceProcessed=true;$(window).on('resize.drupalDisplace',debounce(displace,200));}};Drupal.displace=displace;Object.defineProperty(Drupal.displace,'offsets',{value:offsets,writable:false});Drupal.displace.calculateOffset=calculateOffset;})(jQuery,Drupal,Drupal.debounce);;
'use strict';((Drupal)=>{Drupal.behaviors.ginSticky={attach:()=>{once('ginSticky','.region-sticky-watcher').forEach(()=>{const observer=new IntersectionObserver(([e])=>{const regionSticky=document.querySelector('.region-sticky');regionSticky.classList.toggle('region-sticky--is-sticky',e.intersectionRatio<1);regionSticky.toggleAttribute('data-offset-top',e.intersectionRatio<1);Drupal.displace(true);},{threshold:[1]});const element=document.querySelector('.region-sticky-watcher');if(element)observer.observe(element);});}};})(Drupal);;
